#!/usr/bin/env bash
# Vendors the carrier build toolchain `archival run` embeds.
#
# The toolchain is https://github.com/archival-dev/carriers-toolchain, the build
# every place that runs a carrier shares. The binary carries its `embedded`
# bundle, one file that imports nothing but node's own modules, and a crate has
# to contain what it embeds, so the bundle is committed here rather than fetched
# at build time.
#
# Usage: ./update-carriers-toolchain.sh <commit or tag>
set -euo pipefail

REF="${1:?usage: update-carriers-toolchain.sh <commit or tag>}"
REPO="https://github.com/archival-dev/carriers-toolchain"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/src/binary/carriers/toolchain.mjs"

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

git clone --quiet "${REPO}.git" "${WORK}/toolchain"
git -C "${WORK}/toolchain" checkout --quiet "${REF}"
COMMIT="$(git -C "${WORK}/toolchain" rev-parse HEAD)"
(cd "${WORK}/toolchain" && npm ci --no-audit --no-fund > /dev/null && npm run --silent bundle)

{
  echo "// Generated by update-carriers-toolchain.sh -- do not edit by hand."
  echo "// ${REPO} at ${COMMIT}"
  cat "${WORK}/toolchain/dist/embedded.mjs"
} > "${OUT}"

echo "Wrote ${OUT} from ${COMMIT}"
